// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/inventory/inventory.proto

package mu_micro_book_srv_inventory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Inventory service

type InventoryService interface {
	Sell(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Confirm(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type inventoryService struct {
	c    client.Client
	name string
}

func NewInventoryService(name string, c client.Client) InventoryService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "mu.micro.book.srv.inventory"
	}
	return &inventoryService{
		c:    c,
		name: name,
	}
}

func (c *inventoryService) Sell(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Inventory.Sell", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryService) Confirm(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Inventory.Confirm", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Inventory service

type InventoryHandler interface {
	Sell(context.Context, *Request, *Response) error
	Confirm(context.Context, *Request, *Response) error
}

func RegisterInventoryHandler(s server.Server, hdlr InventoryHandler, opts ...server.HandlerOption) error {
	type inventory interface {
		Sell(ctx context.Context, in *Request, out *Response) error
		Confirm(ctx context.Context, in *Request, out *Response) error
	}
	type Inventory struct {
		inventory
	}
	h := &inventoryHandler{hdlr}
	return s.Handle(s.NewHandler(&Inventory{h}, opts...))
}

type inventoryHandler struct {
	InventoryHandler
}

func (h *inventoryHandler) Sell(ctx context.Context, in *Request, out *Response) error {
	return h.InventoryHandler.Sell(ctx, in, out)
}

func (h *inventoryHandler) Confirm(ctx context.Context, in *Request, out *Response) error {
	return h.InventoryHandler.Confirm(ctx, in, out)
}
