// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package file

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 文件字节内容
type FileByte struct {
	Byte                 []byte   `protobuf:"bytes,1,opt,name=byte,proto3" json:"byte,omitempty"`
	Len                  int64    `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileByte) Reset()         { *m = FileByte{} }
func (m *FileByte) String() string { return proto.CompactTextString(m) }
func (*FileByte) ProtoMessage()    {}
func (*FileByte) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{0}
}

func (m *FileByte) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileByte.Unmarshal(m, b)
}
func (m *FileByte) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileByte.Marshal(b, m, deterministic)
}
func (m *FileByte) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileByte.Merge(m, src)
}
func (m *FileByte) XXX_Size() int {
	return xxx_messageInfo_FileByte.Size(m)
}
func (m *FileByte) XXX_DiscardUnknown() {
	xxx_messageInfo_FileByte.DiscardUnknown(m)
}

var xxx_messageInfo_FileByte proto.InternalMessageInfo

func (m *FileByte) GetByte() []byte {
	if m != nil {
		return m.Byte
	}
	return nil
}

func (m *FileByte) GetLen() int64 {
	if m != nil {
		return m.Len
	}
	return 0
}

// 文件传输完成后返回文件信息
type FileMsg struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileMsg) Reset()         { *m = FileMsg{} }
func (m *FileMsg) String() string { return proto.CompactTextString(m) }
func (*FileMsg) ProtoMessage()    {}
func (*FileMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{1}
}

func (m *FileMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileMsg.Unmarshal(m, b)
}
func (m *FileMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileMsg.Marshal(b, m, deterministic)
}
func (m *FileMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileMsg.Merge(m, src)
}
func (m *FileMsg) XXX_Size() int {
	return xxx_messageInfo_FileMsg.Size(m)
}
func (m *FileMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FileMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FileMsg proto.InternalMessageInfo

func (m *FileMsg) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type DealFileRequest struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Param                string   `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealFileRequest) Reset()         { *m = DealFileRequest{} }
func (m *DealFileRequest) String() string { return proto.CompactTextString(m) }
func (*DealFileRequest) ProtoMessage()    {}
func (*DealFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{2}
}

func (m *DealFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealFileRequest.Unmarshal(m, b)
}
func (m *DealFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealFileRequest.Marshal(b, m, deterministic)
}
func (m *DealFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealFileRequest.Merge(m, src)
}
func (m *DealFileRequest) XXX_Size() int {
	return xxx_messageInfo_DealFileRequest.Size(m)
}
func (m *DealFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DealFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DealFileRequest proto.InternalMessageInfo

func (m *DealFileRequest) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *DealFileRequest) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

type DealFileRespond struct {
	Md5                  string   `protobuf:"bytes,1,opt,name=md5,proto3" json:"md5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealFileRespond) Reset()         { *m = DealFileRespond{} }
func (m *DealFileRespond) String() string { return proto.CompactTextString(m) }
func (*DealFileRespond) ProtoMessage()    {}
func (*DealFileRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{3}
}

func (m *DealFileRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealFileRespond.Unmarshal(m, b)
}
func (m *DealFileRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealFileRespond.Marshal(b, m, deterministic)
}
func (m *DealFileRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealFileRespond.Merge(m, src)
}
func (m *DealFileRespond) XXX_Size() int {
	return xxx_messageInfo_DealFileRespond.Size(m)
}
func (m *DealFileRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_DealFileRespond.DiscardUnknown(m)
}

var xxx_messageInfo_DealFileRespond proto.InternalMessageInfo

func (m *DealFileRespond) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func init() {
	proto.RegisterType((*FileByte)(nil), "FileByte")
	proto.RegisterType((*FileMsg)(nil), "FileMsg")
	proto.RegisterType((*DealFileRequest)(nil), "DealFileRequest")
	proto.RegisterType((*DealFileRespond)(nil), "DealFileRespond")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_9188e3b7e55e1162) }

var fileDescriptor_9188e3b7e55e1162 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xcb, 0xcc, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe0, 0xe2, 0x70, 0xcb, 0xcc, 0x49, 0x75, 0xaa,
	0x2c, 0x49, 0x15, 0x12, 0xe2, 0x62, 0x49, 0xaa, 0x2c, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x09, 0x02, 0xb3, 0x85, 0x04, 0xb8, 0x98, 0x73, 0x52, 0xf3, 0x24, 0x98, 0x14, 0x18, 0x35, 0x98,
	0x83, 0x40, 0x4c, 0x25, 0x35, 0x2e, 0x76, 0x90, 0x0e, 0xdf, 0xe2, 0x74, 0x21, 0x69, 0x2e, 0x4e,
	0x90, 0x51, 0xf1, 0x79, 0x89, 0xb9, 0x10, 0x5d, 0x9c, 0x41, 0x1c, 0x20, 0x01, 0xbf, 0xc4, 0xdc,
	0x54, 0x25, 0x17, 0x2e, 0x7e, 0x97, 0xd4, 0xc4, 0x1c, 0x90, 0xda, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4,
	0xe2, 0x12, 0xbc, 0xea, 0x85, 0x44, 0xb8, 0x58, 0x0b, 0x12, 0x8b, 0x12, 0x73, 0xc1, 0x76, 0x71,
	0x06, 0x41, 0x38, 0x4a, 0xca, 0xc8, 0xa6, 0x14, 0x17, 0xe4, 0xe7, 0xa5, 0x80, 0x9c, 0x94, 0x9b,
	0x62, 0x0a, 0xd5, 0x0f, 0x62, 0x1a, 0x45, 0x72, 0xb1, 0x80, 0x14, 0x08, 0xc9, 0x43, 0x69, 0x4e,
	0x3d, 0x98, 0x9f, 0xa4, 0x38, 0xf4, 0xa0, 0x8e, 0x55, 0x62, 0xd0, 0x60, 0x14, 0x32, 0xe0, 0xe2,
	0x80, 0x99, 0x26, 0x24, 0xa0, 0x87, 0xe6, 0x3c, 0x29, 0x64, 0x11, 0xb0, 0x55, 0x4a, 0x0c, 0x49,
	0x6c, 0xe0, 0x60, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x30, 0xcc, 0x73, 0x50, 0x34, 0x01,
	0x00, 0x00,
}
