// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service/payment.proto

package mu_micro_book_srv_payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payments struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	BookId               int64    `protobuf:"varint,3,opt,name=bookId,proto3" json:"bookId,omitempty"`
	OrderId              int64    `protobuf:"varint,4,opt,name=orderId,proto3" json:"orderId,omitempty"`
	InvHistoryId         int64    `protobuf:"varint,5,opt,name=invHistoryId,proto3" json:"invHistoryId,omitempty"`
	State                int32    `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	CreatedTime          int64    `protobuf:"varint,7,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          int64    `protobuf:"varint,8,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payments) Reset()         { *m = Payments{} }
func (m *Payments) String() string { return proto.CompactTextString(m) }
func (*Payments) ProtoMessage()    {}
func (*Payments) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e25d9f3c2465994, []int{0}
}

func (m *Payments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payments.Unmarshal(m, b)
}
func (m *Payments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payments.Marshal(b, m, deterministic)
}
func (m *Payments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payments.Merge(m, src)
}
func (m *Payments) XXX_Size() int {
	return xxx_messageInfo_Payments.Size(m)
}
func (m *Payments) XXX_DiscardUnknown() {
	xxx_messageInfo_Payments.DiscardUnknown(m)
}

var xxx_messageInfo_Payments proto.InternalMessageInfo

func (m *Payments) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Payments) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Payments) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *Payments) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *Payments) GetInvHistoryId() int64 {
	if m != nil {
		return m.InvHistoryId
	}
	return 0
}

func (m *Payments) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Payments) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Payments) GetUpdatedTime() int64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

type Request struct {
	OrderId              int64    `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e25d9f3c2465994, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *Request) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e25d9f3c2465994, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e25d9f3c2465994, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*Payments)(nil), "mu.micro.book.srv.payment.Payments")
	proto.RegisterType((*Request)(nil), "mu.micro.book.srv.payment.Request")
	proto.RegisterType((*Response)(nil), "mu.micro.book.srv.payment.Response")
	proto.RegisterType((*Error)(nil), "mu.micro.book.srv.payment.Error")
}

func init() { proto.RegisterFile("proto/service/payment.proto", fileDescriptor_9e25d9f3c2465994) }

var fileDescriptor_9e25d9f3c2465994 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0xdb, 0x34, 0xe1, 0x8a, 0x18, 0xac, 0x0a, 0x05, 0x58, 0xa2, 0xb0, 0x74, 0x72,
	0xa5, 0x56, 0x42, 0xe2, 0x07, 0x20, 0xd1, 0x09, 0x64, 0xc1, 0xc6, 0x40, 0x6a, 0xdf, 0x60, 0x41,
	0xea, 0x60, 0x3b, 0x95, 0xfa, 0x77, 0xf9, 0x25, 0xc8, 0xe7, 0x14, 0xb5, 0x03, 0xdd, 0xfc, 0x3d,
	0xbf, 0x77, 0xf1, 0xb3, 0x03, 0xb7, 0xad, 0x35, 0xde, 0xcc, 0x1d, 0xda, 0xad, 0x96, 0x38, 0x6f,
	0xeb, 0x5d, 0x83, 0x1b, 0xcf, 0x49, 0x65, 0xd7, 0x4d, 0xc7, 0x1b, 0x2d, 0xad, 0xe1, 0x6b, 0x63,
	0x3e, 0xb9, 0xb3, 0x5b, 0xde, 0x1b, 0xaa, 0x9f, 0x04, 0xf2, 0x97, 0xb8, 0x76, 0xec, 0x12, 0x06,
	0x5a, 0x15, 0x49, 0x99, 0xcc, 0x86, 0x62, 0xa0, 0x15, 0xbb, 0x82, 0x71, 0xe7, 0xd0, 0xae, 0x54,
	0x31, 0x20, 0xad, 0xa7, 0xa0, 0x87, 0x41, 0x2b, 0x55, 0x0c, 0xa3, 0x1e, 0x89, 0x15, 0x90, 0x19,
	0xab, 0x28, 0x30, 0xa2, 0x8d, 0x3d, 0xb2, 0x0a, 0x2e, 0xf4, 0x66, 0xfb, 0xa4, 0x9d, 0x37, 0x76,
	0xb7, 0x52, 0x45, 0x4a, 0xdb, 0x47, 0x1a, 0x9b, 0x42, 0xea, 0x7c, 0xed, 0xb1, 0x18, 0x97, 0xc9,
	0x2c, 0x15, 0x11, 0x58, 0x09, 0x13, 0x69, 0xb1, 0xf6, 0xa8, 0x5e, 0x75, 0x83, 0x45, 0x46, 0xc1,
	0x43, 0x29, 0x38, 0xba, 0x56, 0xfd, 0x39, 0xf2, 0xe8, 0x38, 0x90, 0xaa, 0x07, 0xc8, 0x04, 0x7e,
	0x77, 0xe8, 0xfc, 0xe1, 0x11, 0x93, 0xe3, 0x23, 0x4e, 0x21, 0x6d, 0xad, 0x96, 0xd8, 0x77, 0x8d,
	0x50, 0xbd, 0x43, 0x2e, 0xd0, 0xb5, 0x66, 0xe3, 0x30, 0x64, 0x5d, 0x27, 0x25, 0x3a, 0x47, 0xd9,
	0x5c, 0xec, 0x91, 0xdd, 0x43, 0x8a, 0xd6, 0x1a, 0x4b, 0xd9, 0xc9, 0xa2, 0xe4, 0xff, 0x5e, 0x38,
	0x7f, 0x0c, 0x3e, 0x11, 0xed, 0xd5, 0x12, 0x52, 0x62, 0xc6, 0x60, 0x24, 0x8d, 0x42, 0x9a, 0x9b,
	0x0a, 0x5a, 0x87, 0x5b, 0x56, 0xe8, 0x6b, 0xfd, 0x45, 0x53, 0xcf, 0x45, 0x4f, 0x8b, 0x0f, 0xc8,
	0xfa, 0x17, 0x63, 0x6f, 0xf4, 0x78, 0xcf, 0xa1, 0x01, 0xab, 0x4e, 0x7c, 0xb4, 0x6f, 0x7f, 0x73,
	0x77, 0xd2, 0x13, 0x6b, 0x56, 0x67, 0xeb, 0x31, 0xfd, 0x36, 0xcb, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x4f, 0x46, 0x73, 0x16, 0x55, 0x02, 0x00, 0x00,
}
