// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: api/api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/micro/go-micro/v2/api/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Open service

type OpenService interface {
	Fetch(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
}

type openService struct {
	c    client.Client
	name string
}

func NewOpenService(name string, c client.Client) OpenService {
	return &openService{
		c:    c,
		name: name,
	}
}

func (c *openService) Fetch(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.name, "Open.Fetch", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Open service

type OpenHandler interface {
	Fetch(context.Context, *proto1.Request, *proto1.Response) error
}

func RegisterOpenHandler(s server.Server, hdlr OpenHandler, opts ...server.HandlerOption) error {
	type open interface {
		Fetch(ctx context.Context, in *proto1.Request, out *proto1.Response) error
	}
	type Open struct {
		open
	}
	h := &openHandler{hdlr}
	return s.Handle(s.NewHandler(&Open{h}, opts...))
}

type openHandler struct {
	OpenHandler
}

func (h *openHandler) Fetch(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.OpenHandler.Fetch(ctx, in, out)
}
