// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service/service.proto

package mu_micro_book_user_srv_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type Request struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	UserPwd              string   `protobuf:"bytes,3,opt,name=userPwd,proto3" json:"userPwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Request) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Request) GetUserPwd() string {
	if m != nil {
		return m.UserPwd
	}
	return ""
}

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34e2f8c9a3669d2, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "mu.micro.book.user.srv.service.User")
	proto.RegisterType((*Request)(nil), "mu.micro.book.user.srv.service.Request")
	proto.RegisterType((*Response)(nil), "mu.micro.book.user.srv.service.Response")
}

func init() { proto.RegisterFile("proto/service/service.proto", fileDescriptor_a34e2f8c9a3669d2) }

var fileDescriptor_a34e2f8c9a3669d2 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xdd, 0x3f, 0x74, 0xbb, 0x23, 0x88, 0xcc, 0x41, 0x42, 0x05, 0x29, 0x41, 0x70, 0x4f,
	0x23, 0xd4, 0x8b, 0x07, 0x8f, 0xbd, 0x78, 0x11, 0x8d, 0x88, 0x57, 0x6d, 0x77, 0x0e, 0xa1, 0x6c,
	0xb3, 0x26, 0x4d, 0xc5, 0x6f, 0x2f, 0x99, 0x6e, 0xeb, 0xcd, 0x9e, 0xf2, 0xde, 0xe3, 0xe5, 0x47,
	0x5e, 0xe0, 0xb2, 0xf7, 0x6e, 0xe3, 0x6e, 0x03, 0xfb, 0xad, 0x5d, 0xf2, 0xfe, 0x24, 0x49, 0xf1,
	0xaa, 0x8b, 0xd4, 0xd9, 0xa5, 0x77, 0xb4, 0x70, 0x6e, 0x45, 0x31, 0xb0, 0xa7, 0xe0, 0xb7, 0x34,
	0xb4, 0xf4, 0x03, 0x94, 0x6f, 0x81, 0x3d, 0x9e, 0x41, 0x6e, 0x5b, 0x95, 0x4d, 0xb3, 0xa6, 0x30,
	0xb9, 0x6d, 0x11, 0xa1, 0x5c, 0x7f, 0x76, 0xac, 0xf2, 0x69, 0xd6, 0xd4, 0x46, 0x34, 0x9e, 0x43,
	0xd1, 0x7f, 0xb7, 0xaa, 0x90, 0x28, 0x49, 0xfd, 0x0e, 0x95, 0xe1, 0xaf, 0xc8, 0x61, 0x83, 0x17,
	0x30, 0x4a, 0xf0, 0xc7, 0xb9, 0x40, 0x6a, 0x33, 0x38, 0x9c, 0xc0, 0x38, 0xa9, 0xa7, 0x3f, 0xd8,
	0xc1, 0xa3, 0x82, 0x2a, 0xe9, 0xe7, 0x03, 0x74, 0x6f, 0xf5, 0x1c, 0xc6, 0x86, 0x43, 0xef, 0xd6,
	0x81, 0xf1, 0x1e, 0xca, 0x14, 0x0b, 0xf7, 0x74, 0x76, 0x4d, 0xff, 0x2f, 0xa2, 0x34, 0xc7, 0xc8,
	0x8d, 0xd9, 0x0a, 0xaa, 0xd7, 0x5d, 0x8a, 0x1f, 0x50, 0xbf, 0x44, 0xf6, 0x3f, 0x32, 0xf6, 0xe6,
	0x18, 0x63, 0x18, 0x35, 0x69, 0x8e, 0x17, 0x77, 0x8f, 0xd4, 0x27, 0x8b, 0x91, 0x7c, 0xf8, 0xdd,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x0d, 0xfb, 0xca, 0x8f, 0x01, 0x00, 0x00,
}
