// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamMessage struct {
	Namespace            string            `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id                   string            `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Fields               []*Field          `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Payload              []*Payload        `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty"`
	Extends              map[string]string `protobuf:"bytes,5,rep,name=extends,proto3" json:"extends,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StreamMessage) Reset()         { *m = StreamMessage{} }
func (m *StreamMessage) String() string { return proto.CompactTextString(m) }
func (*StreamMessage) ProtoMessage()    {}
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *StreamMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMessage.Unmarshal(m, b)
}
func (m *StreamMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMessage.Marshal(b, m, deterministic)
}
func (m *StreamMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMessage.Merge(m, src)
}
func (m *StreamMessage) XXX_Size() int {
	return xxx_messageInfo_StreamMessage.Size(m)
}
func (m *StreamMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMessage proto.InternalMessageInfo

func (m *StreamMessage) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *StreamMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StreamMessage) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *StreamMessage) GetPayload() []*Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *StreamMessage) GetExtends() map[string]string {
	if m != nil {
		return m.Extends
	}
	return nil
}

type Field struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Payload struct {
	Value                []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type StreamResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResponse) Reset()         { *m = StreamResponse{} }
func (m *StreamResponse) String() string { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()    {}
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *StreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse.Unmarshal(m, b)
}
func (m *StreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse.Marshal(b, m, deterministic)
}
func (m *StreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse.Merge(m, src)
}
func (m *StreamResponse) XXX_Size() int {
	return xxx_messageInfo_StreamResponse.Size(m)
}
func (m *StreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse proto.InternalMessageInfo

func (m *StreamResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type MsgByte struct {
	Byte                 []byte   `protobuf:"bytes,1,opt,name=byte,proto3" json:"byte,omitempty"`
	Len                  int64    `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgByte) Reset()         { *m = MsgByte{} }
func (m *MsgByte) String() string { return proto.CompactTextString(m) }
func (*MsgByte) ProtoMessage()    {}
func (*MsgByte) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *MsgByte) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgByte.Unmarshal(m, b)
}
func (m *MsgByte) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgByte.Marshal(b, m, deterministic)
}
func (m *MsgByte) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgByte.Merge(m, src)
}
func (m *MsgByte) XXX_Size() int {
	return xxx_messageInfo_MsgByte.Size(m)
}
func (m *MsgByte) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgByte.DiscardUnknown(m)
}

var xxx_messageInfo_MsgByte proto.InternalMessageInfo

func (m *MsgByte) GetByte() []byte {
	if m != nil {
		return m.Byte
	}
	return nil
}

func (m *MsgByte) GetLen() int64 {
	if m != nil {
		return m.Len
	}
	return 0
}

type HeartBeatRequest struct {
	AreYouOk             string   `protobuf:"bytes,1,opt,name=areYouOk,proto3" json:"areYouOk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatRequest) Reset()         { *m = HeartBeatRequest{} }
func (m *HeartBeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRequest) ProtoMessage()    {}
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *HeartBeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRequest.Unmarshal(m, b)
}
func (m *HeartBeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartBeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRequest.Merge(m, src)
}
func (m *HeartBeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRequest.Size(m)
}
func (m *HeartBeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRequest proto.InternalMessageInfo

func (m *HeartBeatRequest) GetAreYouOk() string {
	if m != nil {
		return m.AreYouOk
	}
	return ""
}

type HeartBeatRespond struct {
	ImOK                 string   `protobuf:"bytes,1,opt,name=imOK,proto3" json:"imOK,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatRespond) Reset()         { *m = HeartBeatRespond{} }
func (m *HeartBeatRespond) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRespond) ProtoMessage()    {}
func (*HeartBeatRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *HeartBeatRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRespond.Unmarshal(m, b)
}
func (m *HeartBeatRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRespond.Marshal(b, m, deterministic)
}
func (m *HeartBeatRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRespond.Merge(m, src)
}
func (m *HeartBeatRespond) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRespond.Size(m)
}
func (m *HeartBeatRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRespond.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRespond proto.InternalMessageInfo

func (m *HeartBeatRespond) GetImOK() string {
	if m != nil {
		return m.ImOK
	}
	return ""
}

func init() {
	proto.RegisterType((*StreamMessage)(nil), "StreamMessage")
	proto.RegisterMapType((map[string]string)(nil), "StreamMessage.ExtendsEntry")
	proto.RegisterType((*Field)(nil), "Field")
	proto.RegisterType((*Payload)(nil), "Payload")
	proto.RegisterType((*StreamResponse)(nil), "StreamResponse")
	proto.RegisterType((*MsgByte)(nil), "MsgByte")
	proto.RegisterType((*HeartBeatRequest)(nil), "HeartBeatRequest")
	proto.RegisterType((*HeartBeatRespond)(nil), "HeartBeatRespond")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0x4d, 0xab, 0xd3, 0x40,
	0x14, 0x7d, 0x49, 0x5e, 0x93, 0x97, 0xeb, 0xb3, 0x3e, 0x07, 0x91, 0x10, 0x45, 0xcb, 0x2c, 0x24,
	0xb8, 0x98, 0x42, 0x8b, 0x20, 0x5d, 0x16, 0x2a, 0x82, 0x84, 0xca, 0xb8, 0x72, 0x39, 0x35, 0xd7,
	0x10, 0x9a, 0x2f, 0x33, 0x13, 0x31, 0xff, 0xdb, 0x1f, 0x20, 0x33, 0x99, 0xb4, 0xe6, 0xed, 0xce,
	0x39, 0xf7, 0xce, 0x3d, 0xe7, 0x84, 0x40, 0x58, 0xc9, 0x9c, 0xb5, 0x5d, 0xa3, 0x1a, 0xfa, 0xd7,
	0x81, 0xa7, 0xdf, 0x54, 0x87, 0xa2, 0x4a, 0x51, 0x4a, 0x91, 0x23, 0x79, 0x0d, 0x61, 0x2d, 0x2a,
	0x94, 0xad, 0xf8, 0x81, 0x91, 0xb3, 0x72, 0x92, 0x90, 0x5f, 0x05, 0xb2, 0x04, 0xb7, 0xc8, 0x22,
	0xd7, 0xc8, 0x6e, 0x91, 0x91, 0x37, 0xe0, 0xff, 0x2c, 0xb0, 0xcc, 0x64, 0xe4, 0xad, 0xbc, 0xe4,
	0xc9, 0xc6, 0x67, 0x9f, 0x34, 0xe5, 0x56, 0x25, 0x14, 0x82, 0x56, 0x0c, 0x65, 0x23, 0xb2, 0xe8,
	0xd6, 0x2c, 0xdc, 0xb1, 0xaf, 0x23, 0xe7, 0xd3, 0x80, 0x7c, 0x80, 0x00, 0xff, 0x28, 0xac, 0x33,
	0x19, 0x2d, 0xcc, 0xce, 0x2b, 0x36, 0x8b, 0xc4, 0x0e, 0xe3, 0xf4, 0x50, 0xab, 0x6e, 0xe0, 0xd3,
	0x6e, 0xbc, 0x83, 0xfb, 0xff, 0x07, 0xe4, 0x01, 0xbc, 0x33, 0x0e, 0x36, 0xb2, 0x86, 0xe4, 0x05,
	0x2c, 0x7e, 0x8b, 0xb2, 0x47, 0x9b, 0x77, 0x24, 0x3b, 0xf7, 0xa3, 0x43, 0xd7, 0xb0, 0x30, 0x39,
	0x09, 0x81, 0x5b, 0x5d, 0xce, 0xbe, 0x32, 0x58, 0x6b, 0x6a, 0x68, 0xa7, 0x57, 0x06, 0xd3, 0xb7,
	0x10, 0xd8, 0xdc, 0xd7, 0xab, 0xce, 0xca, 0xbb, 0x5c, 0xa5, 0x09, 0x2c, 0xc7, 0xd0, 0x1c, 0x65,
	0xdb, 0xd4, 0x12, 0xc9, 0x4b, 0xf0, 0xa5, 0x12, 0xaa, 0x97, 0xf6, 0xb8, 0x65, 0x74, 0x0d, 0x41,
	0x2a, 0xf3, 0xfd, 0xa0, 0x8c, 0xd3, 0x69, 0x50, 0xa3, 0xfb, 0x3d, 0x37, 0x58, 0xd7, 0x28, 0xb1,
	0x36, 0xe6, 0x1e, 0xd7, 0x90, 0x32, 0x78, 0xf8, 0x8c, 0xa2, 0x53, 0x7b, 0x14, 0x8a, 0xe3, 0xaf,
	0x1e, 0xa5, 0x22, 0x31, 0xdc, 0x89, 0x0e, 0xbf, 0x37, 0xfd, 0xf1, 0x6c, 0xcf, 0x5f, 0x38, 0x7d,
	0x37, 0xdb, 0xd7, 0x69, 0x4c, 0xcf, 0xa2, 0x3a, 0x7e, 0x99, 0x7a, 0x6a, 0xbc, 0x29, 0x21, 0x4c,
	0x65, 0x3e, 0xa6, 0x26, 0xef, 0xc1, 0x4b, 0x65, 0x4e, 0x96, 0xf3, 0x4f, 0x1f, 0x3f, 0x63, 0xf3,
	0x56, 0xf4, 0x26, 0x71, 0xc8, 0x16, 0xc2, 0x8b, 0x01, 0x79, 0xce, 0x1e, 0x87, 0x8b, 0x67, 0x92,
	0xf1, 0xa7, 0x37, 0x27, 0xdf, 0xfc, 0x70, 0xdb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x41,
	0x11, 0x60, 0x7d, 0x02, 0x00, 0x00,
}
