// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/nsq.proto

package mu_micro_nsq_demo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DemoEvent struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Current              int64    `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DemoEvent) Reset()         { *m = DemoEvent{} }
func (m *DemoEvent) String() string { return proto.CompactTextString(m) }
func (*DemoEvent) ProtoMessage()    {}
func (*DemoEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2b4a76ced779080, []int{0}
}

func (m *DemoEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoEvent.Unmarshal(m, b)
}
func (m *DemoEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoEvent.Marshal(b, m, deterministic)
}
func (m *DemoEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoEvent.Merge(m, src)
}
func (m *DemoEvent) XXX_Size() int {
	return xxx_messageInfo_DemoEvent.Size(m)
}
func (m *DemoEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DemoEvent proto.InternalMessageInfo

func (m *DemoEvent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DemoEvent) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func init() {
	proto.RegisterType((*DemoEvent)(nil), "mu.micro.nsq.demo.DemoEvent")
}

func init() { proto.RegisterFile("proto/nsq.proto", fileDescriptor_e2b4a76ced779080) }

var fileDescriptor_e2b4a76ced779080 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2b, 0x2e, 0xd4, 0x03, 0xb3, 0x84, 0x04, 0x73, 0x4b, 0xf5, 0x72, 0x33, 0x93,
	0x8b, 0xf2, 0xf5, 0x40, 0x62, 0x29, 0xa9, 0xb9, 0xf9, 0x4a, 0xa6, 0x5c, 0x9c, 0x2e, 0xa9, 0xb9,
	0xf9, 0xae, 0x65, 0xa9, 0x79, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xac, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x12, 0x5c, 0xec, 0xc9, 0xa5, 0x45, 0x45, 0xa9, 0x79,
	0x25, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x30, 0x6e, 0x12, 0x1b, 0xd8, 0x40, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x49, 0x86, 0xe3, 0x6e, 0x63, 0x00, 0x00, 0x00,
}
